%Code by Sudip Nayak B220061
%DSB-SC and SSB Signal
t = 0 : 0.001 : 1 ;
Am = 2 ;
Ac = 1 ;
fm = 2 ;
fc = 50 ;
m = Am * cos(2*pi*fm*t);
c = Ac * cos(2*pi*fc*t);
dsbsc = m .* c ;
mh = imag(hilbert(m));
sbu = m .* cos(2*pi*fc*t) - mh .* sin(2*pi*fc*t);
sbl = m .* cos(2*pi*fc*t) + mh .* sin(2*pi*fc*t);
subplot(321);
plot(t,m);
title('Modulating Signal');
xlabel('Time');
ylabel('Amplitude');
subplot(322);
title('Carrier Signal');
plot(t,c);
title('Carrier Signal');
xlabel('Time');
ylabel('Amplitude');
subplot(323);
plot(t,dsbsc);
title('DSB-SC Signal');
xlabel('Time');
ylabel('Amplitude');
subplot(324);
plot(t,sbu);
xlabel("Time");
ylabel('Amplitude');
title('SSB-SC Upper Side Band Signal');
subplot(325);
plot(t,sbl);
title("SSB-SC Lower Side Band Signal");
xlabel('Time');
ylabel('Amplitude');
