a = 4 ;
f = 1000000;
FS = 500000;
t = 0 : 0.001 : 10 ;
x = a * sin ( 2 * pi * f / FS * t );
title("B220066");
subplot(321);
plot(t,x);
xlabel("Time");
ylabel("Amplitude");
title("Sine wave");
subplot(322);
u = abs(fft(x));
plot(u);
title("Sine wave spectrum");
subplot(323);
x = a * square ( 2 * pi * f / FS * t ,0.5);
plot(t,x);
xlabel("Time");
ylabel("Amplitude");
title("Square wave");
subplot(324);
u = abs(fft(x));
plot(u);
title("Square wave spectrum");
subplot(325);
x = a * sawtooth ( 2 * pi * f / FS * t , 0.5);
plot(t,x);
xlabel("Time");
ylabel("Amplitude");
title("Triangle wave");
subplot(326);
u = abs(fft(x));
plot(u);
title("Triangle wave spectrum");
